"""Literals more than one module needs, written once.

Anything here that also appears in the spec is cited from the spec rather than
restated there, per `validators.md` § Cross-file sets.
"""

PACKAGE = "bot-instructions"

# What decides ownership. A file carrying this string at its canonical
# position is this package's; one that does not is the repo's, whatever the
# flags say. It is also a content refusal: no repo or doctrine string may
# carry it, or a value could forge ownership of a file the repo wrote.
MARKER_TOKEN = "generated by bot-instructions"

# The marker comment's closing sentence, fixed by `renders.md` § Common rules.
MARKER_CLOSE = "Edit [bot-instructions] in the effective manifest or the spec copy, then re-render."

# The two fields the marker line varies by, as the classes `renders.md`
# § Common rules holds them to. `spec.py` refuses a version or a recorded path
# outside them, so nothing interpolated into the marker can close the comment
# it sits in.
MARKER_VERSION_CLASS = "A-Za-z0-9.+-"
MARKER_PATH_CLASS = "A-Za-z0-9._/-"

# Macroscope documents this file's grammar as one glob per line, with `#`
# comments and blank lines ignored
# (<https://docs.macroscope.com/bug-detection-and-fixes#macroscope-ignore>),
# so it is the one markdown output whose comments are `#` rather than HTML.
MACROSCOPE_IGNORE_PATH = ".macroscope/ignore.md"

# The tree the pointed file lives in. `orphan` walks it, `repo-effects.writes`
# discloses it, and `[bot-instructions.repo] code_review_path` is refused
# outside it: a marked file anywhere else is one nothing scans once the repo
# moves the key or switches `codex` off. One statement, read by the config
# refusal and by `validators_repo.SCANNED_TREES`.
CODE_REVIEW_TREE = ".github/instructions"

# The pointed file: the one place a repo's complete review doctrine is
# written, and the only destination the `AGENTS.md` region names.
# `[bot-instructions.repo] code_review_path` names another path inside
# CODE_REVIEW_TREE.
DEFAULT_CODE_REVIEW_PATH = f"{CODE_REVIEW_TREE}/code-review.md"

# The whole of the `AGENTS.md` owned region below its marker, fixed by
# `renders.md` § `AGENTS.md` § Code Review Rules. One line, because that file
# is loaded by every harness at every session start and a working session
# never uses the doctrine.
AGENTS_DIRECTIVE = (
    "If you are a review agent reviewing code, read {path} before you comment."
)

# `.coderabbit.yaml`'s permitted prologue, the one line that may precede its
# marker. `renders.md` § Common rules names exactly two prologues, and
# `marker.prologue_for` is the one place that says which paths carry which.
CODERABBIT_SCHEMA_LINE = (
    "# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json"
)

# The vendored CodeRabbit schema's path is fixed by the spec rather than
# configurable: a configurable one is repointable by the same pull request
# whose file the schema judges.
CODERABBIT_SCHEMA_PATH = ".bot-instructions/coderabbit-schema.json"

# `repo-toml.md` § `[bot-instructions.exclusions]` is the only place this string is written.
DERIVED_REASON = (
    "harness render output, owned upstream — a defect here is fixed at the "
    "source and arrives by re-render"
)

# `renders.md` § `.coderabbit.yaml` fixes both the set and the order.
CODERABBIT_TOP_LEVEL = (
    "language",
    "tone_instructions",
    "early_access",
    "enable_free_tier",
    "inheritance",
    "reviews",
    "chat",
    "knowledge_base",
    "code_generation",
    "issue_enrichment",
)

# `renders.md` § `.coderabbit.yaml`, the shipped default when `[bot-instructions.tone]` is
# absent. Under the 250-character cap by construction.
DEFAULT_TONE = (
    "Terse and technical. Give the defect, its triggering input, and the "
    "consequence. No praise, diff restatement, or summary. One finding per "
    "thread. If unsure, name the part you could not verify."
)

DEFAULT_COPILOT_CHARS = 6000
DEFAULT_QODO_LINES = 800

# `repo-toml.md` § `[[bot-instructions.surface]]` — each is a path this package or Macroscope
# already governs.
RESERVED_SURFACE_NAMES = frozenset({"doctrine", "correctness", "ignore", "approvability"})

# Block ids are frozen: `renders.md` names blocks by id, and a rename is a
# breaking change to every render — a consuming repo's `[bot-instructions.doctrine.append]`
# keyed on the old id would silently reach nothing. `doctrine-routing`
# compares against THIS set rather than against the current heading/row pair,
# because renaming a heading and its row together leaves the two sides
# agreeing and the rule unenforced. Changing this tuple is the breaking
# change, made deliberately, in code a reviewer reads.
FROZEN_BLOCK_IDS = (
    "scope",
    "rounds",
    "severity",
    "no-preferences",
    "declined",
    "render-out-of-scope",
    "trust-model",
    "reply-contract",
)

# The routing table's columns, in the order the table writes them.
ROUTING_COLUMNS = (
    "code-review.md",
    ".coderabbit.yaml",
    "pr_agent issues",
    "pr_agent compliance",
    "pr_agent extra",
    "REVIEW.md",
    "macroscope doctrine.md",
)

# The pointed file is where Codex, Copilot and CodeRabbit are all sent, and
# Macroscope reads no second instruction surface, so a block left out of one
# of these reaches those bots nowhere. `doctrine-routing` judges the table
# against this.
ALL_BLOCK_COLUMNS = ("code-review.md", "macroscope doctrine.md")

# The columns whose bot has no file-based review exclusion and whose
# `render-out-of-scope` cell carries a number, so the exclusion paths ride the
# block as prose there.
EXCLUSION_PROSE_COLUMNS = ("code-review.md", "pr_agent issues", "pr_agent extra")

# `repo-toml.md` § `[bot-instructions.cadence]`: the verb set and the half `qodo-parity`
# requires guidance for. The role column is what that validator reads.
QODO_VERBS = {
    "/agentic_review": "review",
    "/review": "review",
    "/agentic_describe": "not review",
    "/describe": "not review",
    "/improve": "not review",
}
