"""Ownership: the marker line this package writes.

A file is this package's when the marker IS its first line — or the first line
after a prologue the format requires above it. Two prologues exist:
`.github/instructions/<name>.instructions.md` and
`.macroscope/correctness/<surface>.md` open with YAML frontmatter, and
`.coderabbit.yaml` opens with the `yaml-language-server` schema line.

The test is that the line opens with the marker, never that the file holds the
token somewhere: a search is satisfied by a quotation, by a token below a
comment that never closed, and by a first line reading `# not generated by
bot-instructions`.

`render`, `adopt` and `orphan` ask that one question of every output.
"""

from .constants import (CODERABBIT_SCHEMA_LINE, MACROSCOPE_IGNORE_PATH,
                        MARKER_CLOSE, MARKER_TOKEN)

HTML = "html"
HASH = "hash"

# The trailing space is the token's word boundary, and `comment` always
# writes one: without it `bot-instructions-not-owned` reads as this
# package's own file, which is the denial `writer` promises to honour.
_OPENER = {HTML: f"<!-- {MARKER_TOKEN} ", HASH: f"# {MARKER_TOKEN} "}


def style_for(path):
    """The comment syntax `path`'s format uses.

    `.macroscope/ignore.md` is markdown by extension only: Macroscope reads it
    as one glob per line with `#` comments, so an HTML comment there is a
    pattern that matches nothing.
    """
    if path.endswith((".yaml", ".yml", ".toml")) or path == MACROSCOPE_IGNORE_PATH:
        return HASH
    return HTML


def comment(style, version, inputs):
    """The marker this package writes. The one statement of its form.

    The HTML form is ONE line, so the whole marker is the line `owns` tests.
    The `#` form runs to two, both of them comments in every format that takes
    it, `.macroscope/ignore.md` included.
    """
    head = f"{MARKER_TOKEN} {version} from {', '.join(inputs)}."
    if style == HTML:
        return f"<!-- {head} {MARKER_CLOSE} -->"
    return f"# {head}\n# {MARKER_CLOSE}"


def _split_prologue(text):
    """`(prologue, body)`: the prologue `text` opens with, and what follows it."""
    if text.startswith("---\n"):
        end = text.find("\n---\n", 3)
        if end != -1:
            return text[: end + 5], text[end + 5:]
    head, sep, rest = text.partition("\n")
    if sep and head.strip() == CODERABBIT_SCHEMA_LINE:
        return head + sep, rest
    return "", text


def owns(path, text):
    """Did this package write `text`? One question, asked everywhere."""
    if text is None:
        return False
    _, body = _split_prologue(text)
    return body.lstrip("\n").startswith(_OPENER[style_for(path)])


def carries_marker(text):
    """Does `text` carry this package's marker, whatever wrote it?

    `orphan`'s question, and the one place the destination does not decide.
    A rendered file copied between destinations whose formats comment
    differently keeps the marker it was written with, and `renders.md`
    § Marker names that copy orphan's case rather than an exotic one. Writes
    stay destination-strict: `owns` is what the replacement gate asks.
    """
    if text is None:
        return False
    _, body = _split_prologue(text)
    body = body.lstrip("\n")
    return any(body.startswith(opener) for opener in _OPENER.values())


def insert(text, marker_text):
    """Put the marker where `owns` looks for it.

    The gap under a prologue is what the renderer writes there: a blank line
    under frontmatter, and none under the schema line, which is itself a `#`
    comment the marker follows directly. `adopt` producing a different shape
    from `render` would show as a diff on the next render of a file nobody
    edited.
    """
    prologue, body = _split_prologue(text)
    if not prologue:
        return marker_text + "\n\n" + text
    gap = "\n" if prologue.endswith("---\n") else ""
    return prologue + gap + marker_text + "\n" + body
