#!/usr/bin/env bash
# The canonical valid render, asserted green, plus the properties a caller
# relies on: reproducibility, the AGENTS.md splice, adopt, and the lock.
#
# § Controls: without one canonical render asserted green, a validator that
# rejects everything satisfies the entire red set.

. "$(dirname "$0")/lib/harness.sh"

repo="$(bi_new_repo canonical)"

expect_green "a fresh repo adopts its hand-written region" adopt --repo "$repo"
expect_green "the canonical TOML renders" render --repo "$repo"
expect_green "and checks clean" check --repo "$repo"

appended="$(bi_new_repo nested-append)" || exit 1
cat >>"$appended/kendex.toml" <<'TOML'

[bot-instructions.doctrine.append]
declined = """
First repository rule.

Second repository rule.
"""
TOML
bi_must adopt --repo "$appended" || exit 1
bi_must render --repo "$appended" || exit 1
if python3 -B - "$BI_ROOT/skills/bot-instructions" "$appended" <<'PY'; then
from pathlib import Path
import sys
sys.path.insert(0, sys.argv[1] + "/scripts")
from lib import spec, tree
doctrine = spec.load(tree.Worktree(sys.argv[1]), "SKILL.md", "schemas/renders.md")
lines = (Path(sys.argv[2]) / "AGENTS.md").read_text().splitlines()
nested = [line for line in lines if line.startswith("  - ")]
assert nested == ["  - First repository rule.", "  - Second repository rule."], nested
parent = "- " + " ".join(doctrine.blocks["declined"].split())
at = lines.index(nested[0])
assert lines[at - 1:at + 2] == [parent, *nested]
PY
  ok "a two-paragraph append becomes two nested AGENTS bullets under its block"
else
  bad "a two-paragraph append becomes two nested AGENTS bullets under its block"
fi

# Reproducible from its inputs: no timestamps and no input hashes, so an
# unrelated re-render is not a diff.
before="$(cat "$repo/.coderabbit.yaml" "$repo/.pr_agent.toml" "$repo/AGENTS.md")"
if bi_must render --repo "$repo"; then
  after="$(cat "$repo/.coderabbit.yaml" "$repo/.pr_agent.toml" "$repo/AGENTS.md")"
  [ "$before" = "$after" ] && ok "a second render writes the same bytes" \
    || bad "a second render writes the same bytes"
fi

for path in .coderabbit.yaml .pr_agent.toml best_practices.md REVIEW.md \
            .github/copilot-instructions.md .github/instructions/tests.instructions.md \
            .macroscope/ignore.md .macroscope/correctness/doctrine.md \
            .macroscope/correctness/tests.md; do
  [ -f "$repo/$path" ] && ok "wrote $path" || bad "wrote $path"
done

# One title. A consumer that lints every tracked markdown file rejects a
# second level-one heading, and Copilot reads the levels below all the same.
if [ "$(grep -c '^# ' "$repo/.github/copilot-instructions.md")" -eq 1 ] \
   && grep -q '^## Code review calibration$' "$repo/.github/copilot-instructions.md" \
   && grep -q '^### scope$' "$repo/.github/copilot-instructions.md"; then
  ok 'copilot-instructions.md carries one level-one heading, calibration below it'
else
  bad 'copilot-instructions.md carries one level-one heading, calibration below it' \
      "$(grep '^#' "$repo/.github/copilot-instructions.md" | head -4 | tr '\n' ' ')"
fi

# `.macroscope/ignore.md` is markdown by extension only. Macroscope documents
# it as one glob per line with `#` comments and blank lines ignored
# (../references/limits.md § Macroscope cites the page), so an HTML comment there
# is a pattern matching nothing, the marker included.
if grep -qF '<!--' "$repo/.macroscope/ignore.md"; then
  bad 'ignore.md carries no HTML comment' \
      "$(grep -F '<!--' "$repo/.macroscope/ignore.md" | tr '\n' ' ')"
else
  ok 'ignore.md carries no HTML comment'
fi
if head -1 "$repo/.macroscope/ignore.md" | grep -q '^# generated by bot-instructions'; then
  ok "ignore.md's marker line opens with #"
else
  bad "ignore.md's marker line opens with #" "$(head -1 "$repo/.macroscope/ignore.md")"
fi
# Every line that is neither blank nor a comment is one glob: no whitespace
# inside it, so a reason or a stray prose line would show here as a pattern.
if grep -v '^#' "$repo/.macroscope/ignore.md" | grep -v '^$' | grep -q '[[:space:]]'; then
  bad 'every non-comment line of ignore.md is a single glob' \
      "$(grep -v '^#' "$repo/.macroscope/ignore.md" | grep -v '^$' | grep '[[:space:]]' | tr '\n' ' ')"
else
  ok 'every non-comment line of ignore.md is a single glob'
fi

# The generator owns exactly the slice from the heading to the next heading at
# that level or above, and never the rest.
grep -q '^# fixture$' "$repo/AGENTS.md" && ok "the splice leaves the repo's own heading" \
  || bad "the splice leaves the repo's own heading"
grep -q '^## Something else$' "$repo/AGENTS.md" && ok "the splice leaves the following section" \
  || bad "the splice leaves the following section"
grep -q 'Tracked: <FIX-n>' "$repo/AGENTS.md" && ok "[bot-instructions.repo] tracker substitutes into reply-contract" \
  || bad "[bot-instructions.repo] tracker substitutes into reply-contract"
grep -q '\.claude/agents/\*\*' "$repo/AGENTS.md" \
  && ok "the exclusion set rides render-out-of-scope into AGENTS.md" \
  || bad "the exclusion set rides render-out-of-scope into AGENTS.md"
grep -q '\.claude/settings\.json' "$repo/AGENTS.md" \
  && bad "a merged harness file was derived as an exclusion" \
  || ok "a harness root's own files are not derived: the repo owns .claude/settings.json"

# A block without an append remains one bullet with no blank line inside.
grep -q '^- Author replies are .* a label it knows\.$' "$repo/AGENTS.md" \
  && ok "the reply-contract block is one bullet on one line, paragraphs joined" \
  || bad "the reply-contract block is one bullet on one line, paragraphs joined"

# `--staged` judges one coherent state: a worktree input that moved on does
# not decide what the staged outputs are compared against.
git -C "$repo" add -A >/dev/null 2>&1
printf '\n[[bot-instructions.exclusions.path]]\nglob = "docs/**"\nreason = "prose"\n' >> "$repo/kendex.toml"
expect_green "--staged ignores a worktree TOML the index does not carry" check --staged --repo "$repo"
expect_red drift "the worktree check reds on the same state" check --repo "$repo"
git -C "$repo" checkout -- kendex.toml

# kendex installs a skill by symlinking `.agents/skills/<name>` at its source,
# so the documented `--spec` value is a symlink to a directory. The two roots
# an operator names are resolved once at startup.
link="$BI_TMP/spec-link"
rm -f "$link"
ln -s "$BI_ROOT/skills/bot-instructions" "$link"
expect_green "--spec through a symlink to the package resolves" \
  check --repo "$repo" --spec "$link"
repo_link="$BI_TMP/repo-link"
rm -f "$repo_link"
ln -s "$repo" "$repo_link"
expect_green "--repo through a symlink to the repository resolves" check --repo "$repo_link"

# The AGENTS.md splice is a read-modify-write, and it splices the bytes the
# write phase itself read. An edit landing immediately BEFORE that read is in
# those bytes, so the run must carry it through — a splice fed from a
# separate read made before the edit computes its output from that stale copy
# and drops the edit, reporting success. Run in-process against the real verb,
# because a shell cannot land a write inside another process's write phase on
# demand.
window="$(bi_rendered_repo write-window)" || exit 1
if python3 - "$BI_ROOT/skills/bot-instructions" "$window" <<'PROBE'; then
import os, sys
PKG, repo = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import fsutil, run, verbs, tree

EDIT = "\nan editor landed here\n"
agents = os.path.join(repo, "AGENTS.md")

def ctx():
    return run.Context(repo, tree.Worktree(repo), tree.Worktree(PKG),
                       ("SKILL.md", "schemas/renders.md"), "render",
                       ("SKILL.md", "schemas/renders.md"))

def edit():
    with open(agents, "a") as fh:
        fh.write(EDIT)

def render_with(hook):
    original = fsutil.read_text
    fsutil.read_text = lambda *a, **kw: hook(original, *a, **kw)
    try:
        verbs.render_verb(ctx(), repo)
        return None
    except Exception as exc:
        return str(exc)
    finally:
        fsutil.read_text = original

once = []
def before_read(original, root, rel):
    if rel == "AGENTS.md" and not once:
        once.append(True)
        edit()
    return original(root, rel)

failed = render_with(before_read)
if not once:
    sys.exit("the write phase never read AGENTS.md, so this probe proved nothing")
if failed is not None:
    sys.exit(f"the render refused an edit its own read carried: {failed}")
if EDIT not in open(agents).read():
    sys.exit("the render reported success and dropped an edit it had read")

# The control: nothing injected, so the render must still write.
if render_with(lambda o, *a: o(*a)) is not None:
    sys.exit("the control render failed")
PROBE
  ok "the splice carries an edit the write phase itself read"
else
  bad "the splice carries an edit the write phase itself read"
fi

# A flag a verb accepts and ignores is the shape this package refuses
# everywhere else, and `adopt` is the one-time verb that writes: a run meant
# to preview would have taken the files over.
for verb in check adopt; do
  bi_run "$verb" --dry-run --repo "$repo"
  if [ "$bi_status" -eq 2 ] && printf '%s\n' "$bi_out" | grep -q -- '--dry-run is a render mode'; then
    ok "--dry-run is refused on $verb, naming the verb"
  else
    bad "--dry-run is refused on $verb, naming the verb" "exit $bi_status: $bi_out"
  fi
done

# The every-flag-false return, and a dry run, both write nothing and say so.
nothing="$(bi_minimal_repo nothing-enabled)"
printf '%s' "$BI_MIN_HEAD" > "$nothing/kendex.toml"
expect_green 'a render with every [bot-instructions.bots] flag false writes nothing' render --repo "$nothing"

dry="$(bi_new_repo dry-run-preview)"
bi_commit "$dry"
expect_green 'a dry run validates and previews the set' render --dry-run --repo "$dry"
if git -C "$dry" status --porcelain | grep -q .; then
  bad 'and writes nothing' "$(git -C "$dry" status --porcelain | tr '\n' ' ')"
else
  ok 'and writes nothing'
fi

# `renders.md` § Common rules: repo text is never reflowed, `tone_instructions`
# alone excepted. `[bot-instructions.repo] summary` reaches three surfaces, and the doctrine
# paragraph-joiner would put a two-line summary on one line at two of them
# while `.pr_agent.toml` carried it unreflowed.
if python3 - "$repo" <<'SUMMARY'; then
import sys
repo = sys.argv[1]
want = ("fixture is a small repository the bot-instructions suites render end to end. It\n"
        "has one skill render tree, one harness render tree, and one test directory.")
assert "\n" in want, "the fixture summary is no longer multi-line"
missing = [rel for rel in (".github/copilot-instructions.md",
                           ".macroscope/correctness/doctrine.md",
                           ".pr_agent.toml")
           if want not in open(repo + "/" + rel).read()]
if missing:
    sys.exit("reflowed in: " + ", ".join(missing))
SUMMARY
  ok 'a multi-line [bot-instructions.repo] summary keeps its line breaks on every surface'
else
  bad 'a multi-line [bot-instructions.repo] summary keeps its line breaks on every surface'
fi

# `exclude_globs` renders as prose on the three surfaces with no exclude field
# of their own, one blank line under the instructions. Appended with a space
# it joins the closing fence of a fenced `instructions`, which then closes
# nothing, and the sentence and everything after it render as code.
fenced="$(bi_new_repo fenced-surface)"
{
  cat "$BI_FIXTURES/canonical.toml"
  cat <<'SURFACE'

[[bot-instructions.surface]]
name = "fenced"
globs = ["src/**"]
exclude_globs = ["src/tests/**"]
instructions = """
Run the example before reporting a defect against it.

```
kendex render --dry-run
```
"""
SURFACE
} > "$fenced/kendex.toml"
bi_must adopt --repo "$fenced" || exit 1
bi_must render --repo "$fenced" || exit 1
if python3 - "$BI_ROOT/skills/bot-instructions" "$fenced" <<'PROBE'; then
import os, sys
PKG, repo = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import run, tree

SENTENCE = "These rules do not cover src/tests/**."


def outside_a_fence(where, text):
    """The sentence is there, at fence depth zero, and no fence is left open."""
    if SENTENCE not in text:
        sys.exit(where + ": the exclusion sentence is not in the output at all")
    depth = 0
    seen = False
    for line in text.split("\n"):
        if line.strip().startswith("```"):
            depth = 1 - depth
            continue
        if SENTENCE in line:
            seen = True
            if depth:
                sys.exit(where + ": the exclusion sentence is inside a code fence")
    if not seen:
        sys.exit(where + ": the exclusion sentence never appears on a line of its own")
    if depth:
        sys.exit(where + ": a code fence is left open")


outside_a_fence(".github/instructions/fenced.instructions.md",
                open(repo + "/.github/instructions/fenced.instructions.md").read())
outside_a_fence("best_practices.md", open(repo + "/best_practices.md").read())
ctx = run.Context(repo, tree.Worktree(repo), tree.Worktree(PKG),
                  ("SKILL.md", "schemas/renders.md"), "check",
                  ("SKILL.md", "schemas/renders.md"))
doc = ctx.build.data[".coderabbit.yaml"]
entries = [e for e in doc["reviews"]["path_instructions"]
           if SENTENCE in e["instructions"]]
if not entries:
    sys.exit(".coderabbit.yaml: no path_instructions entry carries the sentence")
outside_a_fence(".coderabbit.yaml path_instructions", entries[0]["instructions"])
PROBE
  ok 'an exclusion sentence after a fenced code block lands outside the fence'
else
  bad 'an exclusion sentence after a fenced code block lands outside the fence'
fi

# The region ends at a setext heading's TEXT, not its underline. A terminator
# that reads only `#` headings runs the owned span through the repo's own
# section, and the splice then deletes it.
if python3 - "$BI_ROOT/skills/bot-instructions" <<'PROBE'; then
import sys
sys.path.insert(0, sys.argv[1] + "/scripts")
from lib import render

doc = "\n".join(["# fixture", "", "## Code Review Rules", "", "body", "",
                 "Next section", "---", "", "repo prose", ""])
lines = doc.split("\n")
span = render.bounds(doc)
if span is None:
    sys.exit("bounds found no single region")
if lines[span[1]] != "Next section":
    sys.exit(f"the region ran past the setext heading, to {lines[span[1]]!r}")
if "repo prose" in lines[span[0] + 1:span[1]]:
    sys.exit("the splice would replace the repo's own prose")
PROBE
  ok 'the owned region ends above a setext heading, not through it'
else
  bad 'the owned region ends above a setext heading, not through it'
fi

# No bootstrap exemption: an unmarked region is the repo's whatever its body
# holds, and a whitespace test would be exactly the boundary `renders.md`
# § `AGENTS.md` says does not exist.
empty_region="$(bi_new_repo empty-region)"
printf '# fixture\n\nx\n\n## Code Review Rules\n\n## Something else\n\nText.\n' \
  > "$empty_region/AGENTS.md"
git -C "$empty_region" add -A >/dev/null 2>&1
expect_message "run \`adopt\` to take it over" \
  'an unmarked region with an empty body is refused, not written' \
  render --repo "$empty_region"

# Each `path_filters` entry carries its reason, from the same two sources
# `.macroscope/ignore.md` draws on. Both surfaces that subtract for real say
# why; a bare list is indistinguishable from a mistake at the next read.
if python3 - "$repo" <<'PROBE'; then
import sys
repo = sys.argv[1]
lines = open(repo + "/.coderabbit.yaml").read().split("\n")
start = next(i for i, ln in enumerate(lines) if ln.strip() == "path_filters:")
entries, comments = 0, 0
for i in range(start + 1, len(lines)):
    body = lines[i].strip()
    if body.endswith(":") and not body.startswith(("#", "-", "!")):
        break
    if body.startswith("- "):
        entries += 1
        if not lines[i - 1].strip().startswith("#"):
            sys.exit(f"path_filters entry on line {i + 1} carries no reason above it")
        if len(lines[i - 1].strip()) < 4:
            sys.exit(f"the reason above line {i + 1} is empty")
        comments += 1
if entries == 0:
    sys.exit("read no path_filters entries, so this proved nothing")
if entries != comments:
    sys.exit(f"{entries} entries and {comments} reasons")
PROBE
  ok 'every path_filters entry carries its reason above it'
else
  bad 'every path_filters entry carries its reason above it'
fi

# Every path the marker interpolates into a comment meets the class that
# cannot close one. The control injects one through the manifest read, the
# input list's one repo-derived member, and drives `cli.main` so it asserts on
# what the run PRINTS: the refusal has to reach the operator attributed to the
# validator that owns the injected source, not to `kendex.toml`.
if python3 - "$BI_ROOT/skills/bot-instructions" "$repo" <<'PROBE'; then
import contextlib, io, os, sys
PKG, repo = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import cli, manifest

original = manifest.resolve

def leaky(t):
    resolved = original(t)
    resolved.paths.insert(0, "kendex.toml --> and live reviewer instructions")
    return resolved

manifest.resolve = leaky
err = io.StringIO()
try:
    with contextlib.redirect_stderr(err):
        status = cli.main(["check", "--repo", repo, "--spec", PKG])
finally:
    manifest.resolve = original
printed = err.getvalue()
if status == 0:
    sys.exit("a marker input path outside the class was accepted")
if "refuses" not in printed:
    sys.exit(f"refused, but not by the marker-path clause: {printed.strip()}")
if not printed.startswith("exclusion-consistency:"):
    sys.exit(f"refused without naming the validator whose clause it is: {printed.strip()}")
PROBE
  ok 'a marker input path outside the class is refused, naming its validator'
else
  bad 'a marker input path outside the class is refused, naming its validator'
fi

# One `ls-files` per run, whichever tree the verb reads. `manifest.derive`
# asks per harness row, so an uncached read spawns git once per row. `Index`
# caches; `Worktree` has to answer the same way.
repo="$(bi_rendered_repo one-ls-files)" || exit 1
python3 - "$repo/kendex.toml" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read().replace('harnesses = ["claude"]',
                           'harnesses = ["claude", "codex", "cursor", "gemini"]')
open(p, "w").write(s)
PY
for h in .codex .cursor .gemini; do
  mkdir -p "$repo/$h/x"
  printf 'x\n' > "$repo/$h/x/f.md"
done
git -C "$repo" add -A >/dev/null 2>&1
# Re-rendered against the wider harness list, so the run being counted is a
# clean one. A run that reds part way through reads fewer trees than a whole
# one and the count would prove nothing.
bi_must render --repo "$repo" || exit 1
bi_commit "$repo"
if python3 - "$BI_ROOT/skills/bot-instructions" "$repo" <<'PROBE'; then
import contextlib, io, os, sys
PKG, repo = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import cli, tree

calls = []
original = tree._git

def counted(root, args):
    calls.append(root)
    return original(root, args)

tree._git = counted
try:
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        status = cli.main(["check", "--repo", repo, "--spec", PKG])
finally:
    tree._git = original
if status != 0:
    sys.exit("the fixture did not check clean, so the count proves nothing")
if len(calls) != 1:
    sys.exit(f"four harness rows spawned {len(calls)} index reads, not one")
PROBE
  ok 'the tracked list is read once per run, whatever the harness count'
else
  bad 'the tracked list is read once per run, whatever the harness count'
fi

# A failure with no message still names a cause. `KeyboardInterrupt` and
# `SystemExit` stringify to nothing, and a Ctrl-C part way through is the case
# the partial-set report exists for, so the test is on the STRING: the
# exception is truthy whatever its message.
repo="$(bi_new_repo interrupted-adopt)"
mkdir -p "$repo/.github/instructions"
for f in .coderabbit.yaml .pr_agent.toml best_practices.md REVIEW.md; do
  printf 'the repo wrote this\n' > "$repo/$f"
done
git -C "$repo" add -A >/dev/null 2>&1
if python3 - "$BI_ROOT/skills/bot-instructions" "$repo" <<'PROBE'; then
import os, sys
PKG, repo = sys.argv[1], sys.argv[2]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import run, tree, verbs
from lib.errors import RenderError

ctx = run.Context(repo, tree.Worktree(repo), tree.Worktree(PKG),
                  ("SKILL.md", "schemas/renders.md"), "check",
                  ("SKILL.md", "schemas/renders.md"))
seen = []
original = verbs._adopt_file


def interrupting(ctx_, root_fd, path):
    seen.append(path)
    if len(seen) == 3:
        raise KeyboardInterrupt
    return original(ctx_, root_fd, path)


verbs._adopt_file = interrupting
try:
    verbs.adopt_verb(ctx, repo)
    sys.exit("the probe never interrupted the adopt")
except RenderError as exc:
    report = str(exc)
finally:
    verbs._adopt_file = original
if len(seen) < 3:
    sys.exit(f"the probe interrupted after {len(seen)} files, so it proved nothing")
if "adopt failed: KeyboardInterrupt" not in report:
    sys.exit(f"the cause is not named: {report!r}")
if "adopted " not in report:
    sys.exit(f"the partial-set report is gone: {report!r}")
PROBE
  ok 'an interrupted adopt names the interrupt as its cause'
else
  bad 'an interrupted adopt names the interrupt as its cause'
fi

bi_summary
