#!/usr/bin/env bash
# `toml-schema`'s content refusals. Each row here is one red control over a
# cell of `repo-toml.md` § The content refusals, whose predicates are encoded
# once in `scripts/lib/refusals.py`. It is NOT a control per cell of that
# table: a row carries several predicates and only the combinations below are
# exercised, so `[bot-instructions.repo] name` is here for its marker refusal
# and not its others, and `[bot-instructions.tone] coderabbit` has no row at
# all. The cross-file probe checks that the table and the three structures
# encoding it agree, which is the table's SHAPE rather than each input. The
# schema's shape clauses are `toml-schema.test.sh`.
#
# Every control starts from a TOML with every `[bot-instructions.bots]` flag
# false, a legitimate state that renders nothing, and pins the
# `(<predicate> refusal, <row>)` suffix `refusals.apply` appends: a row
# carries several predicates, `apply` raises on the first to match, so a
# control that held only the validator's name passed whichever predicate was
# doing the work.

. "$(dirname "$0")/lib/harness.sh"

repo="$(bi_minimal_repo toml-refusals)"

# One record per mutation, read by `bi_toml_table`: `append` rows are the
# mutation under `$BI_MIN_HEAD`, `whole` rows the file entire. A setext
# heading, `Injected` over `===`, reaches `.github/copilot-instructions.md`
# and `.macroscope/correctness/doctrine.md` as an H1, which an ATX-only
# refusal does not see. A control character arrives through TOML's own
# escapes: the `\u0001` in the summary row parses cleanly and yields a
# literal byte, so the value is decoded by the time the refusal sees it.
# `read -d ''` rather than `$(cat <<'ROWS' ...)`: Bash 3.2 scans a
# here-document inside a command substitution for quotes, and a row carrying
# an odd number of double quotes runs its parse past the closing parenthesis.
IFS= read -r -d '' rows <<'ROWS'
a heading in [bot-instructions.repo] summary, indented, which is the wide predicate|whole|check|(heading refusal, [bot-instructions.repo] summary)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = """
text
  ## forged
"""
END
a setext heading in [bot-instructions.repo] summary|whole|check|(heading refusal, [bot-instructions.repo] summary)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = """
Injected
===
"""
END
a `---` line under text in [bot-instructions.repo] summary|whole|check|(heading refusal, [bot-instructions.repo] summary)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = """
text
---
more
"""
END
the marker text in [bot-instructions.repo] summary|whole|check|(marker refusal, [bot-instructions.repo] summary)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = "generated by bot-instructions is not a repo's to say"
END
a control character in [bot-instructions.repo] summary|whole|check|(control refusal, [bot-instructions.repo] summary)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = "a\u0001b"
END
the marker text in [bot-instructions.repo] name|whole|check|(marker refusal, [bot-instructions.repo] name)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "generated by bot-instructions"
summary = "A fixture repository."
END
a newline in [bot-instructions.repo] tracker, which no destination carries|whole|check|(single-line refusal, [bot-instructions.repo] tracker)
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = "A fixture repository."
tracker = """
KEN
1
"""
END
comment-close in an exclusion reason|append|check|(comment-close refusal, [[bot-instructions.exclusions.path]] reason)
[[bot-instructions.exclusions.path]]
glob = "a/**"
reason = "ends the comment --> and then some"
END
a newline in an exclusion reason|append|check|(single-line refusal, [[bot-instructions.exclusions.path]] reason)
[[bot-instructions.exclusions.path]]
glob = "a/**"
reason = """
two
lines
"""
END
a toml-delimiter in a [bot-instructions.doctrine.replace] value|append|check|(toml-delimiter refusal, [bot-instructions.doctrine.*] values)
[bot-instructions.doctrine.replace]
scope = "closes its own string \"\"\" then TOML"
END
a heading in a [bot-instructions.doctrine.append] value|append|check|(heading refusal, [bot-instructions.doctrine.*] values)
[bot-instructions.doctrine.append]
scope = """
text
# forged
"""
END
the marker text in a [[bot-instructions.surface]] instructions|append|check|(marker refusal, [[bot-instructions.surface]] instructions)
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "t"
globs = ["a/**"]
instructions = "generated by bot-instructions"
END
ROWS
bi_toml_table 'the content refusals' "$repo" "$rows"

# § Cross-file sets: the content-refusal table is the single statement, and
# three structures encode it. Held against them here, so a row or a marked
# cell present on one side and absent from the other reds.
if python3 - "$BI_ROOT/skills/bot-instructions" <<'PROBE'; then
import os, re, sys
PKG = sys.argv[1]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import refusals
from lib.constants import QODO_VERBS

table = open(os.path.join(PKG, "schemas/repo-toml.md")).read()
rows = [ln for ln in table.split("\n")
        if ln.startswith("| ") and ln.count("|") == 9
        and not ln.startswith("| Input string")
        and not ln.startswith("|---")]
if len(rows) != 10:
    sys.exit(f"read {len(rows)} rows out of the table, expected the documented ten")

# The five columns whose cells are a yes/dash, in the table's order, against
# the predicate names ROWS spells.
COLUMNS = ["heading", "marker", "comment-close", "toml-delimiter", "control"]
# The table's row labels, mapped to the ROWS key or to the structure that owns
# them. Two rows are not content classes and are enforced elsewhere.
ELSEWHERE = {
    "`[[bot-instructions.surface]] globs`, `exclude_globs`, `[[bot-instructions.exclusions.path]] glob`": "globs.check",
    "`[bot-instructions.cadence] qodo_commands` entries": "config._cadence",
}
LABELS = {
    "`[bot-instructions.repo] name`": "[bot-instructions.repo] name",
    "`[bot-instructions.repo] tracker`": "[bot-instructions.repo] tracker",
    "`[bot-instructions.repo] summary`": "[bot-instructions.repo] summary",
    "`[[bot-instructions.surface]] instructions`": "[[bot-instructions.surface]] instructions",
    "`[bot-instructions.doctrine.append]` / `[bot-instructions.doctrine.replace]` values": "[bot-instructions.doctrine.*] values",
    "doctrine block text": "doctrine block text",
    "`[[bot-instructions.exclusions.path]] reason`": "[[bot-instructions.exclusions.path]] reason",
    "`[bot-instructions.tone] coderabbit`": "[bot-instructions.tone] coderabbit",
}
seen = set()
for line in rows:
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    label = cells[0]
    if label in ELSEWHERE:
        seen.add(label)
        continue
    if label not in LABELS:
        sys.exit(f"table row {label!r} is neither a ROWS row nor one of the two "
                 "the table says are enforced elsewhere")
    key = LABELS[label]
    if key not in refusals.ROWS:
        sys.exit(f"table row {label!r} has no {key!r} in refusals.ROWS")
    seen.add(label)
    want = {COLUMNS[i] for i, cell in enumerate(cells[1:6]) if cell == "yes"}
    have = {p for p in refusals.ROWS[key][0] if p in COLUMNS}
    if want != have:
        sys.exit(f"{key!r}: the table marks {sorted(want)} and ROWS runs {sorted(have)}")
    enforced = cells[7]
    owner = refusals.ROWS[key][1]
    if owner not in enforced:
        sys.exit(f"{key!r}: the table's Enforced column says {enforced!r}, ROWS says {owner!r}")
if len(seen) != 10:
    sys.exit(f"matched {len(seen)} of the table's rows")
if set(LABELS.values()) != set(refusals.ROWS):
    sys.exit("refusals.ROWS holds a row the table does not")
# The two the table says live elsewhere, held against the structures that own
# them rather than taken on trust.
from lib import globs
from lib.errors import InputError
try:
    globs.check("a,b", "control")
except InputError:
    pass
else:
    sys.exit("globs.check does not enforce the glob row")
# The verb row has its own table one section up, and its Role column is what
# `qodo-parity` reads. Compared cell by cell: a count passes for ANY role
# assignment.
verbs = {}
for ln in table.split("\n"):
    cells = [c.strip().strip("`") for c in ln.strip().strip("|").split("|")]
    if len(cells) == 3 and cells[0].startswith("/"):
        verbs[cells[0]] = cells[2]
if verbs != QODO_VERBS:
    sys.exit(f"[bot-instructions.cadence] verb table says {verbs}; constants.QODO_VERBS says {QODO_VERBS}")
PROBE
  ok 'the content-refusal table agrees with the three structures that encode it'
else
  bad 'the content-refusal table agrees with the three structures that encode it'
fi

# The class holds three characters ABOVE C0, because a YAML reader breaks a
# line on all three: U+0085 NEL, U+2028 LINE SEPARATOR, U+2029 PARAGRAPH
# SEPARATOR. A `reason` carrying one is emitted as the comment above its
# entry, and the reader takes the rest as a `path_filters:` key whose first
# entry has no `!` — the allowlist state. Each is paired with the ordinary
# value it deviates from by that one character. Written as TOML escapes: a
# literal separator here would be invisible to a reader and to a diff.
repo="$(bi_minimal_repo line-separators)"
mkdir -p "$repo/a"
printf 'x\n' > "$repo/a/f.rs"
git -C "$repo" add -A >/dev/null 2>&1

bi_reason() {
  { printf '%s' "$BI_MIN_HEAD"
    printf '[bot-instructions.exclusions]\n[[bot-instructions.exclusions.path]]\nglob = "a/**"\nreason = "a generated%s tree"\n' "$1"
  } > "$repo/kendex.toml"
}
# Each control pins WHICH PREDICATE fired, not only the validator. This row
# carries `control` and `single-line` both, `apply` raises on the first to
# match, and `splitlines` inside `single-line` breaks on these same three
# characters — so a bare `expect_red toml-schema` passes whichever is doing
# the work. `apply` puts the predicate's name in the message.
for cp in u0085 u2028 u2029; do
  bi_reason ''
  expect_green "an ordinary [[bot-instructions.exclusions.path]] reason, the pair for \\$cp" \
    check --repo "$repo"
  bi_reason "\\$cp"
  expect_clause toml-schema '(control refusal, [[bot-instructions.exclusions.path]] reason)' \
    "a line separator \\$cp in [[bot-instructions.exclusions.path]] reason is the control predicate's refusal" \
    check --repo "$repo"
done

# `single-line`'s own clause, and the one character of it that carries weight.
# `splitlines` DROPS a trailing break, so the predicate appends a `.` before
# counting: without it `"a\n"` and `"a"` both read as one line and a reason
# ending in a newline passes.
bi_reason ''
expect_green 'an ordinary [[bot-instructions.exclusions.path]] reason, the pair below' check --repo "$repo"
{ printf '%s' "$BI_MIN_HEAD"
  printf '[bot-instructions.exclusions]\n[[bot-instructions.exclusions.path]]\nglob = "a/**"\nreason = "a generated tree\\n"\n'
} > "$repo/kendex.toml"
expect_clause toml-schema '(single-line refusal, [[bot-instructions.exclusions.path]] reason)' \
  'a [[bot-instructions.exclusions.path]] reason ending in a newline is the single-line predicate'"'"'s refusal' \
  check --repo "$repo"

# The same character in `[[bot-instructions.surface]] instructions`, which reaches
# `.coderabbit.yaml` inside a block scalar: the text after it would be emitted
# unindented, end the scalar, and leave PyYAML unable to read the file at all.
bi_surface() {
  { printf '%s' "$BI_MIN_HEAD"
    # A surface needs a route for its text, or `toml-schema` reds on the
    # surface set instead and the pair proves nothing about the separator.
    printf '[bot-instructions.bots]\ncodex = true\ncopilot = true\n'
    printf '[[bot-instructions.surface]]\nname = "tests"\nglobs = ["a/**"]\nreviewer_only = true\n'
    printf 'instructions = "An ordinary%s surface."\n' "$1"
  } > "$repo/kendex.toml"
}
# `render --dry-run`, like the empty-instructions control in
# `toml-schema.test.sh`: this pair needs a bot enabled for the surface text to
# have a route, and a fixture with bots on and no rendered outputs reds on
# `drift` under `check`.
bi_surface ''
expect_green 'an ordinary [[bot-instructions.surface]] instructions, the pair below' \
  render --dry-run --repo "$repo"
bi_surface '\u2028'
expect_clause toml-schema '(control refusal, [[bot-instructions.surface]] instructions)' \
  'a line separator in [[bot-instructions.surface]] instructions' \
  render --dry-run --repo "$repo"

bi_summary
