#!/usr/bin/env bash
# `toml-schema`: one red control per rejection clause.
#
# Every control starts from a TOML with every `[bot-instructions.bots]` flag false, which is a
# legitimate state that renders nothing, so each reds on its own mutation and
# not on a neighbour's.

. "$(dirname "$0")/lib/harness.sh"

repo="$(bi_minimal_repo toml-schema)"

# One control from a mutation appended to the minimal head.
c() { bi_control toml-schema "$1" "$repo"; }

# One control from a whole TOML written by the caller.
w() {
  local label
  label="$1"
  cat > "$repo/kendex.toml"
  expect_red toml-schema "$label" check --repo "$repo"
}

# --- the shape set ----------------------------------------------------------
c 'an unknown table' <<'EOF'
[bot-instructions.bot]
codex = true
EOF
c 'an unknown key in a known table' <<'EOF'
[bot-instructions.exclusions]
derive_renders = true
EOF
c 'a value of the wrong type' <<'EOF'
[bot-instructions.bots]
codex = "yes"
EOF
c 'an empty glob list' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "t"
globs = []
instructions = "x"
EOF
c 'an empty surface name' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = ""
globs = ["a/**"]
instructions = "x"
EOF
c 'a malformed surface name' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "Tests"
globs = ["a/**"]
instructions = "x"
EOF
c 'a duplicated surface name' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "t"
globs = ["a/**"]
instructions = "x"
[[bot-instructions.surface]]
name = "t"
globs = ["b/**"]
instructions = "y"
EOF
c 'a reserved surface name' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "correctness"
globs = ["a/**"]
instructions = "x"
EOF
c 'an unknown doctrine block id' <<'EOF'
[bot-instructions.doctrine.append]
no-such-block = "x"
EOF
w 'a schema value other than 1' <<'EOF'
[bot-instructions]
schema = 2
[bot-instructions.repo]
name = "fixture"
summary = "A fixture repository."
EOF

# The required-key clause derives from the Required column of
# `repo-toml.md` § Keys rather than restating which fields are required.
w 'an absent required key stated in prose (schema)' <<'EOF'
[bot-instructions.repo]
name = "fixture"
summary = "A fixture repository."
EOF
w 'an absent required key in a table row ([bot-instructions.repo] name)' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
summary = "A fixture repository."
EOF
w 'an absent required [bot-instructions.repo] summary' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
EOF
c 'an absent required [[bot-instructions.exclusions.path]] reason' <<'EOF'
[[bot-instructions.exclusions.path]]
glob = "a/**"
EOF
c 'an absent required [[bot-instructions.surface]] instructions' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "t"
globs = ["a/**"]
EOF

# --- the content refusals ---------------------------------------------------
# The clauses are the cells of `repo-toml.md` § The content refusals; the
# predicates are that table's, encoded once in `scripts/lib/refusals.py`.
w 'a heading in [bot-instructions.repo] summary, indented, which is the wide predicate' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = """
text
  ## forged
"""
EOF
# A setext heading: `Injected` over `===` reaches
# `.github/copilot-instructions.md` and `.macroscope/correctness/doctrine.md`
# as an H1, which an ATX-only refusal does not see.
w 'a setext heading in [bot-instructions.repo] summary' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = """
Injected
===
"""
EOF
if printf '%s\n' "$bi_out" | grep -q 'heading refusal'; then
  ok 'and the heading refusal is the clause that names it'
else
  bad 'and the heading refusal is the clause that names it' "$bi_out"
fi

w 'a `---` line under text in [bot-instructions.repo] summary' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = """
text
---
more
"""
EOF
w 'the marker text in [bot-instructions.repo] summary' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = "generated by bot-instructions is not a repo's to say"
EOF

# A control character arrives through TOML's own escapes: a backslash-u-0001
# escape parses cleanly and yields a literal byte, so the value is decoded by
# the time the refusal sees it.
printf '[bot-instructions]\nschema = 1\n[bot-instructions.repo]\nname = "fixture"\nsummary = "a\\u0001b"\n' \
  > "$repo/kendex.toml"
expect_red toml-schema 'a control character in [bot-instructions.repo] summary' check --repo "$repo"

w 'the marker text in [bot-instructions.repo] name' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "generated by bot-instructions"
summary = "A fixture repository."
EOF
w 'a newline in [bot-instructions.repo] tracker, which no destination carries' <<'EOF'
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = "A fixture repository."
tracker = """
KEN
1
"""
EOF
c 'comment-close in an exclusion reason' <<'EOF'
[[bot-instructions.exclusions.path]]
glob = "a/**"
reason = "ends the comment --> and then some"
EOF
c 'a newline in an exclusion reason' <<'EOF'
[[bot-instructions.exclusions.path]]
glob = "a/**"
reason = """
two
lines
"""
EOF
c 'a toml-delimiter in a [bot-instructions.doctrine.replace] value' <<'EOF'
[bot-instructions.doctrine.replace]
scope = "closes its own string \"\"\" then TOML"
EOF
c 'a heading in a [bot-instructions.doctrine.append] value' <<'EOF'
[bot-instructions.doctrine.append]
scope = """
text
# forged
"""
EOF
c 'the marker text in a [[bot-instructions.surface]] instructions' <<'EOF'
[bot-instructions.bots]
codex = true
copilot = true
[[bot-instructions.surface]]
name = "t"
globs = ["a/**"]
instructions = "generated by bot-instructions"
EOF

# --- the glob dialect's path-shape clauses ----------------------------------
# The character class catches none of these: every byte in them is permitted,
# and an empty glob has no bytes at all.
g() {
  cat > "$repo/kendex.toml" <<EOF
[bot-instructions]
schema = 1
[bot-instructions.repo]
name = "fixture"
summary = "A fixture repository."
[[bot-instructions.exclusions.path]]
glob = "$2"
reason = "r"
EOF
  expect_red toml-schema "$1" check --repo "$repo"
}
g 'an empty glob' ''
g 'a leading slash' '/src/**'
g 'a trailing slash' 'src/'
g 'a .. component' '../**'
g 'an empty component' 'src//x'
g 'a brace, outside the class' '{a,b}/**'
g 'an extglob, outside the class' '@(a|b)/**'
g 'a comma, which Copilot applyTo splits on' 'a,b'
g 'a comment character, which .coderabbit.yaml reads as a comment' 'a#b'

c 'an exclusion glob declared twice' <<'EOF'
[[bot-instructions.exclusions.path]]
glob = "a/**"
reason = "one"
[[bot-instructions.exclusions.path]]
glob = "a/**"
reason = "two, and the second reason is the one a reader believes"
EOF

c 'an unknown retention key' <<'EOF'
[bot-instructions.retention]
learnings = false
EOF
c 'a retention flag that is not a boolean' <<'EOF'
[bot-instructions.retention]
coderabbit = "no"
EOF

# --- the cross-flag set -----------------------------------------------------
c 'qodo_best_practices true with qodo false' <<'EOF'
[bot-instructions.bots]
qodo_best_practices = true
EOF
c 'copilot true with codex false' <<'EOF'
[bot-instructions.bots]
copilot = true
EOF
c 'surfaces with every route flag false' <<'EOF'
[bot-instructions.bots]
codex = true
qodo = true
[[bot-instructions.surface]]
name = "t"
globs = ["a/**"]
instructions = "x"
EOF
c 'a qodo_commands entry carrying an inline override' <<'EOF'
[bot-instructions.cadence]
qodo_commands = ["/review --pr_reviewer.extra_instructions="]
EOF
c 'a qodo_commands entry outside the verb set' <<'EOF'
[bot-instructions.cadence]
qodo_commands = ["/ask"]
EOF

# Every flag false is a legitimate state and passes: the clauses above are
# narrower than "renders nothing readable".
printf '%s' "$BI_MIN_HEAD" > "$repo/kendex.toml"
expect_green 'every flag false passes and renders nothing' check --repo "$repo"
bi_run render --repo "$repo"
if printf '%s\n' "$bi_out" | grep -q 'nothing to render'; then
  ok 'render says it wrote nothing rather than exiting quietly'
else
  bad 'render says it wrote nothing rather than exiting quietly' "$bi_out"
fi

# A surface whose text is empty renders a `path_instructions` entry with no
# text, a `.instructions.md` with a marker and nothing under it, and a
# best-practices section with no body.
repo="$(bi_new_repo empty-surface)"
python3 - "$repo" "$BI_FIXTURES/canonical.toml" <<'PY'
import re, sys
repo, src = sys.argv[1], sys.argv[2]
# The canonical TOML with one surface's text emptied and nothing else changed,
# so the clause under test is the only one with anything to say. A fixture
# with every route flag false reds `toml-schema` on its own.
text = re.sub(r'(name = "tests".*?instructions = """\n).*?(\n""")', r'\1\2',
              open(src).read(), flags=re.S)
open(repo + "/kendex.toml", "w").write(text)
PY
expect_red toml-schema 'a [[bot-instructions.surface]] whose instructions are empty' \
  render --dry-run --repo "$repo"

# The dialect's class permits `[`, `]` and every byte between them, so a
# reversed range is made of allowed characters and compiles nowhere. Proving
# it compiles at input is what makes it a finding rather than a traceback out
# of the dead-exclusion clause.
repo="$(bi_minimal_repo reversed-class)"
bi_control toml-schema 'a reversed character range, which is in the class and compiles nowhere' "$repo" <<'EOF'

[[bot-instructions.exclusions.path]]
glob = "src/[z-a].rs"
reason = "a range no engine reads"
EOF

# The same clause names WHICH key it read, and quotes the glob the author
# wrote rather than the collapsed form `re` saw — `**/**/` becomes `**/`
# before the compile, and quoting that names a string no file holds.
expect_finding() {
  local want carries label
  want="$1"; carries="$2"; label="$3"; shift 3
  bi_run "$@"
  if [ "$bi_status" -eq 0 ]; then
    bad "$label" "expected $want to red; the run passed"
  elif ! printf '%s\n' "$bi_out" | grep -q "^$want:"; then
    bad "$label" "expected '$want:'; got: $(printf '%s' "$bi_out" | head -1)"
  elif printf '%s\n' "$bi_out" | grep -qF -- "$carries"; then
    ok "$label"
  else
    bad "$label" "expected the finding to carry '$carries'; got: $(printf '%s' "$bi_out" | head -1)"
  fi
}

repo="$(bi_minimal_repo reversed-class-surface)"
{ printf '%s' "$BI_MIN_HEAD"; cat <<'EOF'
[[bot-instructions.surface]]
name = "tests"
globs = ["src/**/**/[z-a].rs"]
reviewer_only = true
instructions = """
A surface whose glob compiles nowhere.
"""
EOF
} > "$repo/kendex.toml"
expect_finding toml-schema '[[bot-instructions.surface]][0] globs[0]:' \
  'a surface glob that compiles nowhere names the key it came from' \
  check --repo "$repo"
expect_finding toml-schema "glob 'src/**/**/[z-a].rs'" \
  'and quotes the glob as written, not the collapsed pattern' \
  check --repo "$repo"

# The derived side: an inventory entry is the one glob source no author wrote
# as a glob, and the refusal has to name the entry that produced it.
repo="$(bi_new_repo reversed-class-derived)"
mkdir -p "$repo/.agents/skills/zw"
printf 'x\n' > "$repo/.agents/skills/zw/SKILL.md"
bi_inventory_add "$repo" '.agents/skills/z[y-a]w/SKILL.md'
git -C "$repo" add -A >/dev/null 2>&1
expect_finding exclusion-consistency '.kendex-generated.json .agents/skills/z[y-a]w' \
  'a derived glob that compiles nowhere names the inventory entry' \
  check --repo "$repo"

# § Cross-file sets: the content-refusal table is the single statement, and
# three structures encode it. Held against them here, so a row or a marked
# cell present on one side and absent from the other reds.
if python3 - "$BI_ROOT/skills/bot-instructions" <<'PROBE'; then
import os, re, sys
PKG = sys.argv[1]
sys.path.insert(0, os.path.join(PKG, "scripts"))
from lib import refusals
from lib.constants import QODO_VERBS

table = open(os.path.join(PKG, "schemas/repo-toml.md")).read()
rows = [ln for ln in table.split("\n")
        if ln.startswith("| ") and ln.count("|") == 9
        and not ln.startswith("| Input string")
        and not ln.startswith("|---")]
if len(rows) != 10:
    sys.exit(f"read {len(rows)} rows out of the table, expected the documented ten")

# The five columns whose cells are a yes/dash, in the table's order, against
# the predicate names ROWS spells.
COLUMNS = ["heading", "marker", "comment-close", "toml-delimiter", "control"]
# The table's row labels, mapped to the ROWS key or to the structure that owns
# them. Two rows are not content classes and are enforced elsewhere.
ELSEWHERE = {
    "`[[bot-instructions.surface]] globs`, `exclude_globs`, `[[bot-instructions.exclusions.path]] glob`": "globs.check",
    "`[bot-instructions.cadence] qodo_commands` entries": "config._cadence",
}
LABELS = {
    "`[bot-instructions.repo] name`": "[bot-instructions.repo] name",
    "`[bot-instructions.repo] tracker`": "[bot-instructions.repo] tracker",
    "`[bot-instructions.repo] summary`": "[bot-instructions.repo] summary",
    "`[[bot-instructions.surface]] instructions`": "[[bot-instructions.surface]] instructions",
    "`[bot-instructions.doctrine.append]` / `[bot-instructions.doctrine.replace]` values": "[bot-instructions.doctrine.*] values",
    "doctrine block text": "doctrine block text",
    "`[[bot-instructions.exclusions.path]] reason`": "[[bot-instructions.exclusions.path]] reason",
    "`[bot-instructions.tone] coderabbit`": "[bot-instructions.tone] coderabbit",
}
seen = set()
for line in rows:
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    label = cells[0]
    if label in ELSEWHERE:
        seen.add(label)
        continue
    if label not in LABELS:
        sys.exit(f"table row {label!r} is neither a ROWS row nor one of the two "
                 "the table says are enforced elsewhere")
    key = LABELS[label]
    if key not in refusals.ROWS:
        sys.exit(f"table row {label!r} has no {key!r} in refusals.ROWS")
    seen.add(label)
    want = {COLUMNS[i] for i, cell in enumerate(cells[1:6]) if cell == "yes"}
    have = {p for p in refusals.ROWS[key][0] if p in COLUMNS}
    if want != have:
        sys.exit(f"{key!r}: the table marks {sorted(want)} and ROWS runs {sorted(have)}")
    enforced = cells[7]
    owner = refusals.ROWS[key][1]
    if owner not in enforced:
        sys.exit(f"{key!r}: the table's Enforced column says {enforced!r}, ROWS says {owner!r}")
if len(seen) != 10:
    sys.exit(f"matched {len(seen)} of the table's rows")
if set(LABELS.values()) != set(refusals.ROWS):
    sys.exit("refusals.ROWS holds a row the table does not")
# The two the table says live elsewhere, held against the structures that own
# them rather than taken on trust.
from lib import globs
from lib.errors import InputError
try:
    globs.check("a,b", "control")
except InputError:
    pass
else:
    sys.exit("globs.check does not enforce the glob row")
# The verb row has its own table one section up, and its Role column is what
# `qodo-parity` reads. Compared cell by cell: a count passes for ANY role
# assignment.
verbs = {}
for ln in table.split("\n"):
    cells = [c.strip().strip("`") for c in ln.strip().strip("|").split("|")]
    if len(cells) == 3 and cells[0].startswith("/"):
        verbs[cells[0]] = cells[2]
if verbs != QODO_VERBS:
    sys.exit(f"[bot-instructions.cadence] verb table says {verbs}; constants.QODO_VERBS says {QODO_VERBS}")
PROBE
  ok 'the content-refusal table agrees with the three structures that encode it'
else
  bad 'the content-refusal table agrees with the three structures that encode it'
fi

# The class holds three characters ABOVE C0, because a YAML reader breaks a
# line on all three: U+0085 NEL, U+2028 LINE SEPARATOR, U+2029 PARAGRAPH
# SEPARATOR. A `reason` carrying one is emitted as the comment above its
# entry, and the reader takes the rest as a `path_filters:` key whose first
# entry has no `!` — the allowlist state. Each is paired with the ordinary
# value it deviates from by that one character. Written as TOML escapes: a
# literal separator here would be invisible to a reader and to a diff.
repo="$(bi_minimal_repo line-separators)"
mkdir -p "$repo/a"
printf 'x\n' > "$repo/a/f.rs"
git -C "$repo" add -A >/dev/null 2>&1

bi_reason() {
  { printf '%s' "$BI_MIN_HEAD"
    printf '[bot-instructions.exclusions]\n[[bot-instructions.exclusions.path]]\nglob = "a/**"\nreason = "a generated%s tree"\n' "$1"
  } > "$repo/kendex.toml"
}
# Each control asserts WHICH PREDICATE fired, not only the validator. This row
# carries `control` and `single-line` both, `apply` raises on the first to
# match, and `splitlines` inside `single-line` breaks on these same three
# characters — so a bare `expect_red toml-schema` passes whichever is doing
# the work. `apply` puts the predicate's name in the message.
for cp in u0085 u2028 u2029; do
  bi_reason ''
  expect_green "an ordinary [[bot-instructions.exclusions.path]] reason, the pair for \\$cp" \
    check --repo "$repo"
  bi_reason "\\$cp"
  expect_red toml-schema "a line separator \\$cp in [[bot-instructions.exclusions.path]] reason" \
    check --repo "$repo"
  if printf '%s\n' "$bi_out" | grep -qF '(control refusal,'; then
    ok "and \\$cp is the control predicate's refusal, not single-line's"
  else
    bad "and \\$cp is the control predicate's refusal, not single-line's" "$bi_out"
  fi
done

# `single-line`'s own clause, and the one character of it that carries weight.
# `splitlines` DROPS a trailing break, so the predicate appends a `.` before
# counting: without it `"a\n"` and `"a"` both read as one line and a reason
# ending in a newline passes.
bi_reason ''
expect_green 'an ordinary [[bot-instructions.exclusions.path]] reason, the pair below' check --repo "$repo"
{ printf '%s' "$BI_MIN_HEAD"
  printf '[bot-instructions.exclusions]\n[[bot-instructions.exclusions.path]]\nglob = "a/**"\nreason = "a generated tree\\n"\n'
} > "$repo/kendex.toml"
expect_red toml-schema 'a [[bot-instructions.exclusions.path]] reason ending in a newline' check --repo "$repo"
if printf '%s\n' "$bi_out" | grep -qF '(single-line refusal,'; then
  ok 'and it is the single-line predicate that refuses it'
else
  bad 'and it is the single-line predicate that refuses it' "$bi_out"
fi

# The same character in `[[bot-instructions.surface]] instructions`, which reaches
# `.coderabbit.yaml` inside a block scalar: the text after it would be emitted
# unindented, end the scalar, and leave PyYAML unable to read the file at all.
bi_surface() {
  { printf '%s' "$BI_MIN_HEAD"
    # A surface needs a route for its text, or `toml-schema` reds on the
    # surface set instead and the pair proves nothing about the separator.
    printf '[bot-instructions.bots]\ncodex = true\ncopilot = true\n'
    printf '[[bot-instructions.surface]]\nname = "tests"\nglobs = ["a/**"]\nreviewer_only = true\n'
    printf 'instructions = "An ordinary%s surface."\n' "$1"
  } > "$repo/kendex.toml"
}
# `render --dry-run`, like the empty-instructions control above: this pair
# needs a bot enabled for the surface text to have a route, and a fixture with
# bots on and no rendered outputs reds on `drift` under `check`.
bi_surface ''
expect_green 'an ordinary [[bot-instructions.surface]] instructions, the pair below' \
  render --dry-run --repo "$repo"
bi_surface '\u2028'
expect_red toml-schema 'a line separator in [[bot-instructions.surface]] instructions' \
  render --dry-run --repo "$repo"

# `[bot-instructions.doctrine]` is typed before it is iterated, the way `_table` types every
# sibling. The STRING is the case that matters: untyped it does not crash, it
# iterates character by character and reports `[bot-instructions.doctrine.r]: unknown table`,
# naming a cause that does not exist. All three arrive as one `toml-schema`
# finding naming `[bot-instructions.doctrine]` and what was found there.
repo="$(bi_new_repo doctrine-type)"
doctrine_is() {
  python3 - "$repo/kendex.toml" "$1" <<'PY'
import sys
p, v = sys.argv[1], sys.argv[2]
s = open(p).read()
key = "[bot-instructions]\n"
assert s.count(key) == 1, "fixture shape changed"
open(p, "w").write(s.replace(key, f"{key}doctrine = {v}\n"))
PY
}
for pair in 'list:[]' 'int:3' 'str:"reply-contract"'; do
  doctrine_is "${pair#*:}"
  bi_run check --repo "$repo"
  if printf '%s\n' "$bi_out" | grep -qF "[bot-instructions.doctrine]: expected a table, got ${pair%%:*}"; then
    ok "a [bot-instructions.doctrine] that is a ${pair%%:*} names the table and what was found"
  else
    bad "a [bot-instructions.doctrine] that is a ${pair%%:*} names the table and what was found" \
      "$(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
  fi
  cp "$BI_FIXTURES/canonical.toml" "$repo/kendex.toml"
done

repo="$(bi_minimal_repo manifest-namespace)"
printf '%s' "$BI_MIN_HEAD" > "$repo/kendex.toml"
cat >> "$repo/kendex.toml" <<'EOF'
[skill-instructions]
dev = "Keep the project rule."
[agent-additional-instructions]
rust = "Keep the agent rule."
[sources.catalog]
path = "catalog"
EOF
expect_green 'unrelated manifest tables do not enter the bot schema' check --repo "$repo"
mv "$repo/kendex.toml" "$repo/kendex-local.toml"
printf 'schema = 6\nis_source_catalog = true\nbot-instructions = false\n' > "$repo/kendex.toml"
expect_green 'source catalog selection also applies with no derived exclusions or install' \
  check --repo "$repo"
printf 'schema = 6\nbot-instructions = "text"\n' > "$repo/kendex-local.toml"
expect_red toml-schema 'a bot configuration scalar is refused as a table error' \
  check --repo "$repo"
expect_message 'kendex-local.toml [bot-instructions]: expected a table' \
  'the scalar refusal identifies the selected file and table' check --repo "$repo"
printf 'schema = 6\n' > "$repo/kendex-local.toml"
expect_red toml-schema 'a missing bot table is refused' \
  check --repo "$repo"

bi_summary
