# Shared fixture builder and assertions for the bot-instructions suites.
#
# § Controls fixes what these have to prove: one red control per rejection
# clause, each asserting on that validator's OWN identity and never on the
# run's exit code.
#
# Sourced, never executed: no mode bit, per this repo's CI convention.

set -u
unset GIT_DIR GIT_COMMON_DIR GIT_WORK_TREE GIT_INDEX_FILE
# The in-process probes import the package from its own tree (the launcher
# itself runs `python3 -B`), and CPython then writes `scripts/lib/__pycache__/`
# beside the source: generated bytes in the package tree, which a refresh
# mirrors into the render.
export PYTHONDONTWRITEBYTECODE=1

BI_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
BI="$BI_ROOT/skills/bot-instructions/scripts/bot-instructions"
BI_FIXTURES="$BI_ROOT/skills/bot-instructions/tests/fixtures"
BI_PASS=0
BI_FAIL=0
# errexit around the one assignment whose failure would leave a variable empty
# and let the trap below run `rm -rf` on it. Scoped rather than file-wide
# because this file is SOURCED by every suite, and a suite under errexit would
# abort on its first failing assertion instead of reporting it.
set -e
BI_TMP="$(mktemp -d)"
set +e
trap 'rm -rf -- "${BI_TMP:?}"' EXIT

ok() { BI_PASS=$((BI_PASS + 1)); printf '  ok   %s\n' "$1"; return 0; }
bad() {
  BI_FAIL=$((BI_FAIL + 1))
  printf '  FAIL %s\n' "$1"
  if [ $# -gt 1 ]; then printf '       %s\n' "$2"; fi
  return 0
}

# A suite that asserted nothing is not a passing suite: a fixture builder
# that exits every case early, or a table whose rows never ran, would
# otherwise report `0 passed, 0 failed` and exit 0.
bi_summary() {
  printf '%s: %d passed, %d failed\n' "$(basename "$0")" "$BI_PASS" "$BI_FAIL"
  if [ "$((BI_PASS + BI_FAIL))" -eq 0 ]; then
    printf '%s: asserted nothing\n' "$(basename "$0")" >&2
    return 1
  fi
  [ "$BI_FAIL" -eq 0 ]
}

# A repo that renders and checks clean: the canonical valid render every red
# control is a single deviation from. Without it a validator that rejects
# everything would satisfy the entire red set.
bi_new_repo() {
  local name repo
  name="$1"
  repo="$BI_TMP/$name"
  rm -rf -- "${repo:?}"
  mkdir -p "$repo/.bot-instructions" "$repo/.agents/skills/dev" "$repo/.claude/agents" "$repo/src/tests"
  git -C "$repo" init -q .
  git -C "$repo" config user.email fixture@example.invalid
  git -C "$repo" config user.name fixture
  cp "$BI_FIXTURES/coderabbit-schema.json" "$repo/.bot-instructions/coderabbit-schema.json"
  printf 'x\n' > "$repo/.agents/skills/dev/SKILL.md"
  printf 'x\n' > "$repo/.claude/agents/a.md"
  printf '{}\n' > "$repo/.claude/settings.json"
  printf 'fn main() {}\n' > "$repo/src/main.rs"
  mkdir -p "$repo/docs/generated"
  printf 'prose\n' > "$repo/docs/guide.md"
  printf 'prose\n' > "$repo/docs/generated/api.md"
  printf '# fixture\n' > "$repo/README.md"
  printf 'x\n' > "$repo/src/tests/t.rs"
  # kendex's writer inventory, which the skill half of `derive_render` reads:
  # the one skill tree and the harness files kendex would have written.
  printf '%s\n' '[".agents/skills/dev/SKILL.md",".claude/agents/a.md",".claude/settings.json",".kendex-generated.json"]' \
    > "$repo/.kendex-generated.json"
  cat > "$repo/AGENTS.md" <<'EOF'
# fixture

Working-agent guidance lives here.

## Code Review Rules

Hand-written today.

## Something else

Text.
EOF
  cp "$BI_FIXTURES/canonical.toml" "$repo/kendex.toml"
  git -C "$repo" add -A >/dev/null 2>&1
  printf '%s\n' "$repo"
}

# A repo already rendered and staged, so `drift` and `orphan` have a baseline.
bi_rendered_repo() {
  local repo
  repo="$(bi_new_repo "$1")"
  bi_must adopt --repo "$repo" || return 1
  bi_must render --repo "$repo" || return 1
  bi_commit "$repo"
  printf '%s\n' "$repo"
}

# A setup run whose failure is a SUITE failure, not a silent precondition: a
# render that wrote nothing leaves whatever the fixture already had, and a
# negative assertion is satisfied by a file the run never touched.
bi_must() {
  local out status
  out="$("$BI" "$@" 2>&1)"
  status=$?
  if [ "$status" -ne 0 ]; then
    # STDERR, not `bad`. Both fixture builders are called as
    # `repo="$(bi_rendered_repo x)"`, so a FAIL line on stdout is captured
    # into `$repo` and the BI_FAIL it increments dies with the subshell.
    BI_FAIL=$((BI_FAIL + 1))
    printf '  FAIL setup: %s exited %s\n' "$*" "$status" >&2
    printf '       %s\n' "$(printf '%s' "$out" | head -3 | tr '\n' ' ')" >&2
    return 1
  fi
  return 0
}

# Record paths in the fixture's writer inventory, as a kendex refresh that
# rendered them would.
bi_inventory_add() {
  local repo
  repo="$1"; shift
  python3 - "$repo/.kendex-generated.json" "$@" <<'PY'
import json, sys
p = sys.argv[1]
paths = json.load(open(p))
paths.extend(sys.argv[2:])
json.dump(sorted(set(paths)), open(p, "w"))
open(p, "a").write("\n")
PY
}

# A commit, so a suite can put a fixture back with `git reset --hard`.
bi_commit() {
  git -C "$1" add -A >/dev/null 2>&1
  git -C "$1" commit -qm fixture >/dev/null 2>&1 || true
}

bi_out=""
bi_status=0
bi_run() {
  bi_out="$("$BI" "$@" 2>&1)"
  bi_status=$?
  return 0
}

# The red control: the run exits 1, the findings status the commit-guards
# lane sorts on, AND the fired set is exactly the one named. Asserting the
# exit code alone passes on any failure at all, and grepping only for the
# wanted prefix leaves a fixture that also trips a neighbour reading as
# coverage. A 2 with a `validator:` line is a could-not-complete misreported
# as a finding, which `exit-codes.test.sh` says the lane cannot tell apart.
#
# `$1` is the whole expected set, space-separated, its FIRST word the clause
# under test. A second name records a mutation that genuinely breaches two
# clauses rather than hiding it.
expect_red() {
  local want label primary fired expected
  want="$1"; label="$2"; shift 2
  primary="${want%% *}"
  expected="$(printf '%s\n' $want | sort -u | tr '\n' ' ')"
  bi_run "$@"
  fired="$(bi_fired)"
  if [ "$bi_status" -eq 0 ]; then
    bad "$label" "expected $primary to red; the run passed"
  elif [ "$bi_status" -ne 1 ]; then
    bad "$label" "expected exit 1 with $primary; exited $bi_status: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
  elif [ "$fired" = "$expected" ]; then
    ok "$label"
  elif printf '%s\n' "$bi_out" | grep -q "^$primary:"; then
    bad "$label" "expected exactly [$expected]; fired: [$fired]"
  else
    bad "$label" "expected '$primary:'; got: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
  fi
}

expect_green() {
  local label
  label="$1"; shift
  bi_run "$@"
  if [ "$bi_status" -eq 0 ]; then ok "$label"
  else bad "$label" "$(printf '%s' "$bi_out" | head -3 | tr '\n' ' ')"; fi
}

# The could-not-complete control: exit 2, the status a refusal outside the
# validator family carries (a `RenderError`, a `SpecError`, a source that
# could not answer), and the message names what it refused. A validator's
# finding is `expect_red`; a finding whose clause matters is `expect_clause`.
expect_message() {
  local want label
  want="$1"; label="$2"; shift 2
  bi_run "$@"
  if [ "$bi_status" -eq 0 ]; then
    bad "$label" "expected a failure; the run passed"
  elif [ "$bi_status" -ne 2 ]; then
    bad "$label" "expected exit 2; exited $bi_status: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
  elif printf '%s\n' "$bi_out" | grep -qF -- "$want"; then ok "$label"
  else bad "$label" "expected '$want'; got: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"; fi
}

# The red control for one clause of a validator that has several: exit 1,
# that validator alone, and the finding naming the clause (the fragment only
# that clause's message carries), so a fixture that also trips a neighbouring
# clause of the same validator cannot pass on the neighbour.
expect_clause() {
  local validator clause label fired
  validator="$1"; clause="$2"; label="$3"; shift 3
  bi_run "$@"
  fired="$(bi_fired)"
  if [ "$bi_status" -ne 1 ]; then
    bad "$label" "expected exit 1 with $validator; exited $bi_status: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
  elif [ "$fired" != "$validator " ]; then
    bad "$label" "expected exactly [$validator ]; fired: [$fired]"
  elif ! bi_carries "$clause"; then
    bad "$label" "expected the finding to name '$clause'; got: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
  else
    ok "$label"
  fi
}

# The validator names in `$bi_out`, sorted, space-separated, one trailing
# space: the set `expect_red` and a table row compare against.
# The tool's own record line leads with the same shape a validator finding
# does, so it is dropped before the set is read: `bot-instructions` is not a
# validator, and counting it would put it in every findings row.
bi_fired() {
  printf '%s\n' "$bi_out" |
    grep -v '^bot-instructions: ' |
    sed -n 's/^\([a-z][a-z-]*\):.*/\1/p' | sort -u | tr '\n' ' '
}

# The run rendered as `rc=<status> out=<data>`, by status class. 0 renders
# the kind of the verb's first line (`clean`, `wrote`, `would-write`,
# `nothing`, `adopted`, `points-at`; any other line verbatim). 1 renders the
# fired validator set. 2 renders the refusal KEY the first line carries
# (`source`, `spec`, `manifest`, `input`, `usage`, `crashed`), or `-` when
# the line carries no record. The value beside the key is a path the run
# resolved, which a row cannot spell; the case below the table asserts a
# whole record, value included. A message's wording is never rendered.
bi_render() {
  local out line
  line="${bi_out%%
*}"
  case "$bi_status" in
    0)
      case "$line" in
        "check clean: "*) out="clean" ;;
        "wrote "*) out="wrote" ;;
        "would write "*) out="would-write" ;;
        "nothing to render: "*) out="nothing" ;;
        "adopted "*) out="adopted" ;;
        "points at "*) out="points-at" ;;
        *) out="$line" ;;
      esac
      ;;
    1) out="$(bi_fired)"; out="${out% }" ;;
    *)
      case "$line" in
        "bot-instructions: "*"="*)
          out="${line#bot-instructions: }"
          out="${out%%=*}"
          ;;
        *) out="-" ;;
      esac
      ;;
  esac
  printf 'rc=%s out=%s' "$bi_status" "$out"
}

# One table. Rows are `label|world|argv|rc|out|says`: `world` is a word list
# the suite's `bi_world` maps onto a fresh fixture (setting `repo`, and
# `BI_SPEC` when the row names a spec copy), `argv` is the verb and its
# flags (`--repo` and any `--spec` are added here), `rc` and `out` are the
# `bi_render` pair, and `says` is a value the message must carry, or `-`.
# A row with an empty field asserts nothing and refuses the run; a table
# that asserted no row exits 2 from its own counter, so a fixture failure
# or a probe run never reads as green. `BI_TABLE_PROBE=1` renders each row's
# outcome instead of asserting it, for writing rows.
bi_table() {
  local title="$1" rows="$2" row label world argv rc out says got field before
  before=$((BI_PASS + BI_FAIL))
  printf '=== %s ===\n' "$title"
  while IFS= read -r row; do
    [ -n "$row" ] || continue
    IFS='|' read -r label world argv rc out says <<EOF
$row
EOF
    for field in "$label" "$world" "$argv" "$rc" "$out" "$says"; do
      [ -n "$field" ] || { printf 'a row with an empty field asserts nothing: %s\n' "$row" >&2; exit 1; }
    done
    BI_SPEC=""
    # shellcheck disable=SC2086
    bi_world $world || { printf 'the world could not be built: %s\n' "$row" >&2; exit 1; }
    if [ -n "$BI_SPEC" ]; then
      # shellcheck disable=SC2086
      bi_run $argv --repo "$repo" --spec "$BI_SPEC"
    else
      # shellcheck disable=SC2086
      bi_run $argv --repo "$repo"
    fi
    got="$(bi_render)"
    if [ "${BI_TABLE_PROBE:-}" = 1 ]; then
      printf '%s => %s\n' "$label" "$got"
      continue
    fi
    if [ "$got" != "rc=$rc out=$out" ]; then
      bad "$label" "want rc=$rc out=$out; got $got: $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
    elif [ "$says" != - ] && ! bi_carries "$says"; then
      bad "$label" "expected the message to carry '$says': $(printf '%s' "$bi_out" | head -2 | tr '\n' ' ')"
    else
      ok "$label"
    fi
  done <<EOF
$rows
EOF
  [ "$((BI_PASS + BI_FAIL))" -gt "$before" ] || {
    printf 'no row was asserted (a probe run renders rows instead)\n' >&2
    exit 2
  }
}

bi_carries() {
  case "$bi_out" in *"$1"*) return 0 ;; esac
  return 1
}

# One table of `[bot-instructions]` mutations, each a record: a header line
# `label|world|argv|clause`, the TOML lines verbatim, and a line reading
# `END`. `world` is how the body reaches `$repo/kendex.toml`: `append`
# writes `$BI_MIN_HEAD` and then the body, `whole` the body alone. `argv` is
# the verb and its flags (`--repo` is added here). `clause` is the fragment
# only that `toml-schema` clause emits, held with `expect_clause`, so a
# mutation that trips a neighbouring clause of the same validator reds. A
# `#` line or a blank line where a header is expected is skipped, so a table
# keeps its sections. A record with an empty field, an unknown world or no
# `END` refuses the run; a table that asserted no row exits 2 from its own
# counter, so a fixture failure or a probe run never reads as green.
# `BI_TABLE_PROBE=1` renders each row's fired set and `toml-schema:` line
# instead of asserting it, for writing rows.
bi_toml_table() {
  local title="$1" repo="$2" rows="$3" row label world argv clause body field before
  before=$((BI_PASS + BI_FAIL))
  printf '=== %s ===\n' "$title"
  while IFS= read -r row; do
    case "$row" in '' | '#'*) continue ;; esac
    IFS='|' read -r label world argv clause <<EOF
$row
EOF
    for field in "$label" "$world" "$argv" "$clause"; do
      [ -n "$field" ] || { printf 'a record with an empty field asserts nothing: %s\n' "$row" >&2; exit 1; }
    done
    body=""
    while IFS= read -r row && [ "$row" != END ]; do
      body="$body$row
"
    done
    [ "$row" = END ] || { printf 'a record with no END line: %s\n' "$label" >&2; exit 1; }
    case "$world" in
      append) printf '%s%s' "$BI_MIN_HEAD" "$body" > "$repo/kendex.toml" ;;
      whole) printf '%s' "$body" > "$repo/kendex.toml" ;;
      *) printf 'unknown world: %s\n' "$world" >&2; exit 1 ;;
    esac
    if [ "${BI_TABLE_PROBE:-}" = 1 ]; then
      # shellcheck disable=SC2086
      bi_run $argv --repo "$repo"
      printf '%s => fired=[%s] rc=%s %s\n' "$label" "$(bi_fired)" "$bi_status" \
        "$(printf '%s\n' "$bi_out" | sed -n 's/^toml-schema: //p')"
      continue
    fi
    # shellcheck disable=SC2086
    expect_clause toml-schema "$clause" "$label" $argv --repo "$repo"
  done <<EOF
$rows
EOF
  [ "$((BI_PASS + BI_FAIL))" -gt "$before" ] || {
    printf 'no row was asserted (a probe run renders rows instead)\n' >&2
    exit 2
  }
}

# Replace one key's value in a fixture TOML by rewriting the whole file from a
# heredoc the caller supplies on stdin.
bi_toml() { cat > "$1/kendex.toml"; }

# Install-only mutations retain the bot configuration in the same manifest.
bi_manifest() {
  python3 -c '
import sys
from pathlib import Path
p = Path(sys.argv[1]) / "kendex.toml"
s = p.read_text()
key = "[bot-instructions]\n"
assert s.count(key) == 1, "fixture shape changed"
p.write_text(sys.stdin.read() + "\n" + key + s.split(key, 1)[1])
' "$1"
}

# A repo with nothing enabled, for the clauses that reject before any flag
# matters. Every `[bot-instructions.bots]` flag false is a legitimate state, so a control here
# reds on its own mutation and on nothing else.
bi_minimal_repo() {
  local name repo
  name="$1"
  repo="$BI_TMP/$name"
  rm -rf -- "${repo:?}"
  mkdir -p "$repo"
  git -C "$repo" init -q .
  printf '# fixture\n\n## Code Review Rules\n\nx\n' > "$repo/AGENTS.md"
  printf '%s\n' "$repo"
}

BI_MIN_HEAD='[bot-instructions]
schema = 1

[bot-instructions.repo]
name = "fixture"
summary = "A fixture repository."
'

# One control: write `$BI_MIN_HEAD` plus the stdin mutation, then assert the
# named validator is the one that reds.
bi_control() {
  local want label repo
  want="$1"; label="$2"; repo="$3"
  { printf '%s' "$BI_MIN_HEAD"; cat; } > "$repo/kendex.toml"
  expect_red "$want" "$label" check --repo "$repo"
}

# A repo that vendors the spec copy inside itself, which is the consumer shape
# and the only one where `--staged` can read the spec copy from the index.
BI_VENDORED_SPEC=".agents/skills/bot-instructions"
# `$2` is where inside the repo the spec copy is vendored, for the controls
# that turn on whether a path is inside; it defaults to the installed one.
bi_vendored_repo() {
  local repo at
  repo="$(bi_rendered_repo "$1")" || return 1
  at="${2:-$BI_VENDORED_SPEC}"
  mkdir -p "$repo/$at/schemas"
  cp "$BI_ROOT/skills/bot-instructions/SKILL.md" "$repo/$at/SKILL.md"
  cp "$BI_ROOT/skills/bot-instructions/schemas/renders.md" "$repo/$at/schemas/renders.md"
  bi_must render --repo "$repo" --spec "$repo/$at" || return 1
  bi_commit "$repo"
  printf '%s\n' "$repo"
}
